In [1]:
import numpy as np

n = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
n

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [2]:
n[:3]  # 取前3个元素

array([10, 20, 30])

In [3]:
n[3:7]  # 取第4到第7个元素

array([40, 50, 60, 70])

In [4]:
n[::2]  # 取所有元素，步长为2

array([10, 30, 50, 70, 90])

In [8]:
n[::-1]  # 反转数组

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])