In [4]:
import numpy as np

n1 = np.array([1, 2, 3], dtype=int)
n2 = np.array([1, 2, 3], dtype='int32')
n3 = np.array([1, 2, 3], dtype='int64')
n4 = np.array([1, 2, 3], dtype='int_')
n5 = np.array([1, 2, 3], dtype='float')
n6 = np.array(['2025-01-01'], dtype='datetime64')
n1, n2, n3, n4, n5, n6

(array([1, 2, 3]),
 array([1, 2, 3], dtype=int32),
 array([1, 2, 3]),
 array([1, 2, 3]),
 array([1., 2., 3.]),
 array(['2025-01-01'], dtype='datetime64[D]'))